
version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: eodum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: eodum
      DB_HOST: db
      DB_PORT: 5432
      JWT_SECRET: supersegreto
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./gdr-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
